#!/usr/bin/env ruby
spec = {
	'.?' => '<',
	'?.' => '>',
	'..' => '+',
	'!!' => '-',
	'!.' => '.',
	'.!' => ',',
	'!?' => '[',
	'?!' => ']'
}

puts File.read(ARGV[0] || '/dev/stdin').scan(/mkay[\.?!]\s+mkay[\.?!]/).map{|i| spec[i.gsub(/[^\.?!]/, '')]}.join
